### ISSUE TITLE
I couldn't load the icons, I configured almost everything correctly, and I suspected a bug.

### ISSUE THREAD

**Issue by surfishs** [LinsMinecraftStudio/TitleChanger#3]
"icon": {
		/* Should window icon be changed?
		   REMEMBER! You must place icons_16x16.png in the 'icons' folder at least!
		   Supported icon sizes:
		   16x16, 32x32, 48x48, 128x128, 256x256
		*/
		"ChangeIcons": true
		
		
![image](https://github.com/LinsMinecraftStudio/TitleChanger/assets/96485650/b9bcaa13-b2d6-4d48-a9e1-4c7fbecc83c3)

**Comment by surfishs** [comment]
[21:56:37] [Thread-28/INFO]: [STDERR]: java.io.IOException: Could not load image: Image not of any known type, or corrupt
[21:56:37] [Thread-28/INFO]: [STDERR]: 	at net.minecraft.class_1011.method_4303(class_1011.java:138)
[21:56:37] [Thread-28/INFO]: [STDERR]: 	at net.minecraft.class_1011.method_4310(class_1011.java:103)
[21:56:37] [Thread-28/INFO]: [STDERR]: 	at net.minecraft.class_1011.method_4309(class_1011.java:94)
[21:56:37] [Thread-28/INFO]: [STDERR]: 	at net.minecraft.class_1041.method_4491(class_1041.java:163)
[21:56:37] [Thread-28/INFO]: [STDERR]: 	at net.minecraft.class_310.md548e86$titlechanger$lambda$titleAndIcon$0$5(class_310.java:33522)
[21:56:37] [Thread-28/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by surfishs** [comment]
[latest.log](https://github.com/LinsMinecraftStudio/TitleChanger/files/11995325/latest.log)

**Comment by lijinhong11** [comment]
You should place icons of five sizes

**Comment by lijinhong11** [comment]
Hmm
I will fix that

**Comment by lijinhong11** [comment]
已在版本[1.9.2](https://modrinth.com/mod/mctitlechanger/version/1.9.2)修复

**Comment by surfishs** [comment]
I didn't see any changes after the fix and I still can't use it.

**Comment by surfishs** [comment]
[18:04:41] [Render thread/WARN]: IM state inconsistent! state=true, im=false
[18:04:41] [pool-14-thread-1/ERROR]: Uncaught exception in thread "pool-14-thread-1"
java.lang.NullPointerException: defaultObj
	at java.util.Objects.requireNonNull(Unknown Source) ~[?:?]
	at java.util.Objects.requireNonNullElse(Unknown Source) ~[?:?]
	at net.minecraft.class_8518.handler$fba000$titlechanger$getIcon(class_8518.java:526) ~[client-intermediary.jar:?]
	at net.minecraft.class_8518.method_51419(class_8518.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_8518.method_51418(class_8518.java:25) ~[client-intermediary.jar:?]
	at net.minecraft.class_1041.method_4491(class_1041.java:158) ~[client-intermediary.jar:?]
	at salt.mmmjjkx.titlechanger.resource.TitleAndIconThread.refreshTitle(TitleAndIconThread.java:29) ~[TitleChanger-1.9.2.jar:?]
	at salt.mmmjjkx.titlechanger.resource.TitleAndIconThread.updateConfig(TitleAndIconThread.java:78) ~[TitleChanger-1.9.2.jar:?]
	at salt.mmmjjkx.titlechanger.resource.TitleAndIconThread.run(TitleAndIconThread.java:55) ~[TitleChanger-1.9.2.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]

**Comment by surfishs** [comment]
[latest.log](https://github.com/LinsMinecraftStudio/TitleChanger/files/12000606/latest.log)

**Comment by surfishs** [comment]
![image](https://github.com/LinsMinecraftStudio/TitleChanger/assets/96485650/6daa4dae-6a17-451a-9cb1-61716c0c8f58)

**Comment by surfishs** [comment]
Pure version, no interfering items
[latest.log](https://github.com/LinsMinecraftStudio/TitleChanger/files/12001174/latest.log)

**Comment by lijinhong11** [comment]
你必须放一个icon_16x16.png文件
否则模组是无法给你替换空的输入流

**Comment by surfishs** [comment]
> 你必须放一个icon_16x16.png文件 否则模组是无法给你替换空的输入流

没有任何用，我想知道你是使用什么图片来进行测试的，我的测试图片都是可以正常使用的。
我按照你的要求，模组依旧没有工作。

**Comment by lijinhong11** [comment]
确实奇怪，但是我的开发环境有用

**Comment by surfishs** [comment]
我再给你一份纯净测试log，它依旧没用

**Comment by surfishs** [comment]
[latest.log](https://github.com/LinsMinecraftStudio/TitleChanger/files/12001421/latest.log)

**Comment by lijinhong11** [comment]
不需要

**Comment by surfishs** [comment]
> 不需要

什么不需要？

**Comment by surfishs** [comment]
我找到问题了

**Comment by lijinhong11** [comment]
这个就是默认的Object有问题 我还在排查错误

**Comment by surfishs** [comment]
![image](https://github.com/LinsMinecraftStudio/TitleChanger/assets/96485650/df6d795b-7383-43bc-92b4-dad55821dc7d)

**Comment by lijinhong11** [comment]
所以？

**Comment by surfishs** [comment]
真是出乎意料之外的错误原因，你应该修改你在配置文件中的描述，改为icon_16x16.png，而不是icons_16x16.png

**Comment by lijinhong11** [comment]
我知道，但是我没怎么仔细看

**Comment by lijinhong11** [comment]
改完结案

**Comment by surfishs** [comment]
总之问题解决了，你应该更加正确的说明格式。
因为我对如何使用闪烁标题的格式同样感到疑惑，我不知道该怎么让它工作。

**Comment by lijinhong11** [comment]
就是注入替换掉闪烁渲染的文字，你可以用Mixin做到

**Comment by surfishs** [comment]
> 就是注入替换掉闪烁渲染的文字，你可以用Mixin做到

我的意思是，我不知道在这里该填什么，怎么填。
![image](https://github.com/LinsMinecraftStudio/TitleChanger/assets/96485650/c5e05728-06fc-409b-9e76-2d15c6065b59)

**Comment by lijinhong11** [comment]
你要这样写:
```
Ababab
Anfpwef
11
```
一行就是一条闪烁文字

**Comment by surfishs** [comment]
256*256的图片什么情况才会被使用？

**Comment by lijinhong11** [comment]
这种我目前还不知道客户端怎么选的图标

**Comment by lijinhong11** [comment]
发了 1.9.2p1

**Comment by surfishs** [comment]
> 这种我目前还不知道客户端怎么选的图标

32*32的会被自动选取，但是256*256好像不会

**Comment by lijinhong11** [comment]
疑似是优先小的

**Comment by surfishs** [comment]
我不知道如何测试低分辨的区别，所以我干脆塞满了全部格式。
![image](https://github.com/LinsMinecraftStudio/TitleChanger/assets/96485650/d5af9dc5-de79-4278-aa0c-18b341355df4)
随它去吧。

**Comment by lijinhong11** [comment]
如果你有兴趣的话 来discord聊吧 我那差不多一个月没说话了
